name: Build DATUM Gateway

on:
    schedule:
        - cron: '0 0 1 * *'
    push:
    pull_request:

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-22.04
          - macos-latest
          - macos-13
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create build directory
        run: mkdir -p build

      - name: Install dependencies
        run: |
          if [ "${{ runner.os }}" = "macOS" ]; then
            brew install coreutils curl jansson libmicrohttpd libsodium
          else
            sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libjansson-dev libmicrohttpd-dev libsodium-dev
          fi

      - name: Build DATUM Gateway
        run: |
          cd build
          cmake ..
          make -j$(nproc)
